# Generated by Django 5.2.4 on 2025-07-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='created',
            new_name='created_at',
        ),
    ]
